[workspace]
resolver = "2"
members = [
  "bin/ck-snes-gui",
  "lib/ck-snes-asm",
  "lib/ck-snes-core",
]

[workspace.package]
authors = ["Lucas Meier <lucas@cronokirby.com>"]
edition = "2024"
version = "0.1.0"
repository = "https://github.com/cronokirby/ck-snes"
license = "MIT"

[workspace.dependencies]
ck-snes-core = { path = "lib/ck-snes-core" }
proptest = "1.8.0"
